### ISSUE TITLE
Feature: binarized RTM import support

### ISSUE THREAD

**Issue by MrClock8163** [MrClock8163/Arma3ObjectBuilder#46]
### Category

Import-Export

### Name of new feature

BMTR import 

### Description

The add-on currently supports import of "plain" RTM animations given a compatible armature. It'd be nice to have support for binarized animations as well in order to import base Arma 3 animations for references.

Binarized RTM format specs are available on the [community wiki](https://community.bistudio.com/wiki/Rtm_Binarised_File_Format).

### Tasks

- [x] data structure implementation
- [x] conversion to plain RTM
- [x] LZO1X decompression python implementation
- [x] import handling
